name: GoReleaser

on:
    workflow_dispatch:
    push:
        branches: ['*']
        paths:
          - 'managed-clusters-onboard-tracking/*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.3'
      - name: Check prior VERSION file
        run: cat ./managed-clusters-onboard-tracking/VERSION

      - name: Increment version
        run: |
          chmod +x ./managed-clusters-onboard-tracking/bump_version.sh
          NEW_VERSION=$(./managed-clusters-onboard-tracking/bump_version.sh)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit version increment
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./managed-clusters-onboard-tracking/VERSION
          git commit -m "Increment version to ${{ env.NEW_VERSION }}"
          git tag ${{ env.NEW_VERSION }}
          git push origin HEAD --tags

      - name: Check updated VERSION file
        run: cat ./managed-clusters-onboard-tracking/VERSION

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --clean
          workdir: ./managed-clusters-onboard-tracking
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}