name: GoReleaser

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.3'
    #   - name: Check prior VERSION file
    #     run: cat ./secure/sysdig-audit-vm-runtime/VERSION

    #   - name: Increment version
    #     run: |
    #       chmod +x ./secure/sysdig-audit-vm-runtime/increment_version.sh
    #       NEW_VERSION=$(./secure/sysdig-audit-vm-runtime/increment_version.sh)
    #       echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    #   - name: Commit version increment
    #     run: |
    #       git config --local user.email "action@github.com"
    #       git config --local user.name "GitHub Action"
    #       git add ./secure/sysdig-audit-vm-runtime/VERSION
    #       git commit -m "Increment version to ${{ env.NEW_VERSION }}"
    #       git tag ${{ env.NEW_VERSION }}
    #       git push origin HEAD --tags

    #   - name: Check updated VERSION file
    #     run: cat ./secure/sysdig-audit-vm-runtime/VERSION

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --clean
          workdir: ./managed-clusters-onboard-tracking
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}